api:
  prefix: /api/v1


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /${segment}
            - id: profile-service
              uri: lb://profile-service
              predicates:
                - Path=/profiles/**
              filters:
                - RewritePath=/profiles/(?<segment>.*), /${segment}
            - id: file-service
              uri: lb://file-service
              predicates:
                - Path=/files/**
              filters:
                - RewritePath=/files/(?<segment>.*), /${segment}
            - id: movie-service
              uri: lb://movie-service
              predicates:
                - Path=/movies/**
              filters:
                - RewritePath=/movies/(?<segment>.*), /${segment}
            - id: review-service
              uri: lb://review-service
              predicates:
                - Path=/reviews/**
              filters:
                - RewritePath=/reviews/(?<segment>.*), /${segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost



app:
  services:
    auth: http://localhost:8080/auth


springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Profile Service
        url: /profiles/v3/api-docs
      - name: File Service
        url: /files/v3/api-docs
      - name: Movie Service
        url: /movies/v3/api-docs
      - name: Review Service
        url: /reviews/v3/api-docs
