--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-26 23:22:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 230 (class 1259 OID 352699)
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review
(
    approved    boolean NOT NULL,
    rating      integer,
    created_at  timestamp(6) without time zone,
    id          bigint  NOT NULL,
    modified_at timestamp(6) without time zone,
    movie_id    bigint  NOT NULL,
    total_likes bigint  NOT NULL,
    user_id     bigint  NOT NULL,
    review_text character varying(255)
);


ALTER TABLE public.review
    OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 352698)
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.review_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


--
-- TOC entry 231 (class 1259 OID 352704)
-- Name: review_like; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review_like
(
    created_at timestamp(6) without time zone,
    review_id  bigint NOT NULL,
    user_id    bigint NOT NULL
);


ALTER TABLE public.review_like
    OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 352709)
-- Name: review_statistic; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review_statistic
(
    movie_id     bigint NOT NULL,
    review1count bigint NOT NULL,
    review2count bigint NOT NULL,
    review3count bigint NOT NULL,
    review4count bigint NOT NULL,
    review5count bigint NOT NULL
);


ALTER TABLE public.review_statistic
    OWNER TO postgres;

--
-- TOC entry 4778 (class 2606 OID 352708)
-- Name: review_like review_like_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review_like
    ADD CONSTRAINT review_like_pkey PRIMARY KEY (review_id, user_id);


--
-- TOC entry 4776 (class 2606 OID 352703)
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- TOC entry 4780 (class 2606 OID 352713)
-- Name: review_statistic review_statistic_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review_statistic
    ADD CONSTRAINT review_statistic_pkey PRIMARY KEY (movie_id);


-- Completed on 2025-08-26 23:22:02

--
-- PostgreSQL database dump complete
--

